CREATE TABLE Cities (
	CityID INT CONSTRAINT PK_CITY_ID PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL
)

CREATE TABLE Customers (
	CustomerID INT CONSTRAINT PK_Customer_ID PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	Birthday DATE,
	CityID INT CONSTRAINT FK_City_ID FOREIGN KEY REFERENCES Cities(CityID)
)

CREATE TABLE Orders (
	OrderID INT CONSTRAINT PK_Order_ID PRIMARY KEY,
	CustomerID INT CONSTRAINT FK_Cust_ID FOREIGN KEY REFERENCES Customers(CustomerID)
)

CREATE TABLE ItemTypes (
	ItemTypeID INT CONSTRAINT PK_ItemType_ID PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL
)

CREATE TABLE Items (
	ItemID INT CONSTRAINT PK_Item_ID PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	ItemTypeID INT CONSTRAINT FK_ItemType_ID REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE OrderItems (
	OrderID INT NOT NULL CONSTRAINT FK_Order_ID FOREIGN KEY REFERENCES Orders(OrderID),
	ItemID INT NOT NULL CONSTRAINT FK_ItemID FOREIGN KEY REFERENCES Items(ItemID)
	CONSTRAINT PK_OrderItems PRIMARY KEY (OrderID, ItemID)
)