CREATE TABLE Students (
	StudentID INT CONSTRAINT PK_STUDENT_ID PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL
)

INSERT INTO Students (Name) VALUES
('Mila'),
('Toni'),
('Ron')

CREATE TABLE Exams (
	ExamID INT CONSTRAINT PK_EXAM_ID PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL
)

INSERT INTO Exams (ExamID, Name) VALUES
(101, 'SpringMVC'),
(102, 'Neo4j'),
(103, 'Oracle 11g')


CREATE TABLE StudentsExams (
	StudentID INT NOT NULL CONSTRAINT FK_STUDENT_ID FOREIGN KEY REFERENCES Students(StudentID),
	ExamID INT NOT NULL CONSTRAINT FK_EXAM_ID FOREIGN KEY REFERENCES Exams(ExamID),
	CONSTRAINT PK_StudentExams PRIMARY KEY (StudentID,ExamID)
)

INSERT INTO StudentsExams (StudentID, ExamID) VALUES
(1, 101),
(1, 102),
(2, 101),
(3, 103),
(2, 102),
(2, 103)